eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL Eureka Server
  instance:
    prefer-ip-address: true
server:
  port: 8084

spring:
  rabbitmq:
    host: rabbitmq-host
    port: 5672
    username: guest
    password: guest
  application:
    name: GameService

jwt:
  secret: U7512_nG32Eu&261hJp-aSd-KjaaDcbQ