spring:
  application:
    name: game-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spam_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8084

jwt:
  secret: U7512_nG32Eu&261hJp-aSd-KjaaDcbQ