spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service  # Проксирование в AuthService
          predicates:
            - Path=/auth/**  # Маршруты, начинающиеся с /auth
          filters:
            - StripPrefix=1  # Удаляем префикс, чтобы запросы правильно маршрутизировались
            - PreserveHostHeader=true  # Добавляем заголовок хоста
            #- AddRequestHeader=Authorization, "Bearer {jwtToken}" # Прокидываем токен, если нужно вручную
        - id: user-service
          uri: lb://user-service  # Проксирование в UserService
          predicates:
            - Path=/users/**  # Маршруты для UserService
          filters:
            - StripPrefix=1  # Удаляем префикс
            - PreserveHostHeader=true  # Обязательно
            #- AddRequestHeader=Authorization, "#{Authorization}"
            #- AddRequestHeader=Authorization, "Bearer {jwtToken}"
        - id: lobby-service
          uri: lb://lobby-service  # Проксирование в LobbyService
          predicates:
            - Path=/lobby/**  # Маршруты для LobbyService
          filters:
            - StripPrefix=1
            - PreserveHostHeader=true
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader=true
server:
  port: 8080

jwt:
  secret: U7512_nG32Eu&261hJp-aSd-KjaaDcbQ
